Repository oracle/centos2ol, pull requests merged in 2021-01, with the labels that each got.

#34 [bug] Fix parameter handling
  centos2ol.sh
Labels: bug

#33 [admin] Add CODEOWNERS file
  .github/CODEOWNERS
Labels: enhancement

#43 Improve documentation with "Known issues"
  README.md
Labels: documentation
